language: node_js
node_js:
- "10"
install:
- docker pull lambci/lambda:build-nodejs8.10
- docker pull lambci/lambda:nodejs8.10
script:
- make plan
deploy:
- provider: script
  script: make apply
  skip_cleanup: true
  on:
    repo: BostonDSA/members
    tags: true
